// A short, plain description for every coin on the site.
export const ABOUT = {
  BTC: 'Bitcoin is the first and largest cryptocurrency, launched in 2009 as peer-to-peer digital money. Its supply is capped at 21 million coins, which is why many people treat it as digital gold.',
  ETH: 'Ethereum is a programmable blockchain that runs smart contracts and decentralised apps. Its coin, ether, pays network fees and helps secure the network through staking.',
  XRP: 'XRP is the token of the XRP Ledger, a network built for fast, low-cost payments and for moving value between currencies.',
  BNB: 'BNB is the token of the BNB Chain ecosystem. It pays network fees and is used across the Binance platform and the apps built on its chain.',
  SOL: 'Solana is a high-speed blockchain known for quick, low-fee transactions. It is used for payments, trading, games and a wide range of apps.',
  TRX: 'TRON is a blockchain popular for cheap, fast transfers, especially of stablecoins such as USDT.',
  DOGE: 'Dogecoin began in 2013 as a light-hearted take on Bitcoin and grew into one of the most widely recognised coins, often used for tipping and small payments.',
  ADA: 'Cardano is a proof-of-stake blockchain developed through peer-reviewed research. It supports smart contracts and apps.',
  LINK: 'Chainlink brings real-world data, such as prices, onto blockchains so that smart contracts can use it.',
  TON: 'Toncoin powers The Open Network, a blockchain first designed for Telegram and now run by its community, used for payments and apps.',
  AVAX: 'Avalanche is a fast smart-contract platform made of several linked chains, known for quick finality and for letting teams launch their own networks.',
  SUI: 'Sui is a newer blockchain built for fast, low-latency apps and games, using the Move programming language.',
  XLM: 'Stellar is a network for moving money cheaply and quickly across borders, connecting banks, payment systems and people.',
  HBAR: 'Hedera is a public network that uses hashgraph consensus. It is designed for fast, low-fee transactions and business use.',
  DOT: 'Polkadot connects many specialised blockchains so they can share security and exchange information.',
  UNI: 'Uniswap is one of the largest decentralised exchanges, where people swap coins directly from their wallets. UNI is its governance token.',
  LTC: 'Litecoin is one of the earliest Bitcoin spin-offs, built for faster and cheaper everyday payments.',
  ZEC: 'Zcash is a cryptocurrency that offers optional private transactions using zero-knowledge proofs.',
  HYPE: 'HYPE is the token of Hyperliquid, a trading platform that runs on its own high-speed blockchain.',
  USDT: 'Tether (USDT) is a stablecoin designed to stay at one US dollar. It is widely used for trading and for moving value between exchanges.',
  USDC: 'USD Coin (USDC) is a stablecoin issued by Circle and designed to stay at one US dollar, backed by dollar reserves.',
};
