import { open } from './harness.mjs';
const h = await open({ standalone: false }); const { page, url } = h;
const cdp = await page.context().newCDPSession(page);
await cdp.send('WebAuthn.enable');
const { authenticatorId } = await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: false, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
await page.goto(url + '/settings/lock'); await page.waitForTimeout(2000);
await page.click('#lock-switch'); await page.waitForTimeout(1200);
await cdp.send('WebAuthn.setUserVerified', { authenticatorId, isUserVerified: false });
await page.evaluate(() => sessionStorage.removeItem('cm-unlock')); await page.reload(); await page.waitForTimeout(3000);
console.log('wrong finger -> still locked:', await page.evaluate(() => document.documentElement.classList.contains('locked')), '|', await page.textContent('.lock-msg'));
await page.screenshot({ path: '/tmp/locked.png' });
await cdp.send('WebAuthn.setUserVerified', { authenticatorId, isUserVerified: true });
await page.click('.lock-go'); await page.waitForTimeout(1500);
console.log('right finger -> unlocked:', !(await page.evaluate(() => document.documentElement.classList.contains('locked'))));
await h.close();
