import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import { start } from './serve.mjs';
const { server, state, url } = await start();
const browser = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 360, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errs = [];
const watch = p => { p.on('pageerror', e => errs.push('PAGEERROR ' + p.url() + ' :: ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text().slice(0, 160)); }); };
watch(page); ctx.on('page', watch);
const cdp = await ctx.newCDPSession(page);
await cdp.send('Emulation.setEmulatedMedia', { features: [{ name: 'display-mode', value: 'standalone' }] });
await page.goto(url + '/app');
await page.waitForTimeout(2500);
const frame = () => page.frames().find(f => f !== page.mainFrame() && f.url().endsWith('/'));
const f = frame();
console.log('frames:', page.frames().map(x => x.url()));
await f.click('.menu-btn, [aria-label*="enu"]').catch(e => console.log('open menu fail', e.message.slice(0,80)));
await page.waitForTimeout(600);
console.log('shell-away after open:', await page.evaluate(() => document.documentElement.classList.contains('shell-away')));
const links = await f.$$eval('.menu a, .menu button', els => els.map(e => (e.textContent || '').trim().replace(/\s+/g,' ').slice(0,30) + ' | ' + (e.getAttribute('href') || e.id || e.className)));
console.log(links.join('\n'));
console.log('ERRORS', errs.slice(0, 20));
await browser.close(); server.close();
