import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import { start } from './serve.mjs';
const { server, url } = await start(4175);
const ctx = await chromium.launchPersistentContext('/tmp/pw-profile-' + Date.now(), { executablePath: process.env.CHROME, args: ['--no-sandbox'], viewport: { width: 360, height: 800 } });
const page = await ctx.newPage();
const bs = await ctx.browser().newBrowserCDPSession().catch(() => null);
const cdp = await ctx.newCDPSession(page);
await cdp.send('Browser.setPermission', { permission: { name: 'notifications' }, setting: 'granted', origin: url }).catch(e => console.log('setPerm', e.message.slice(0, 80)));
await page.goto(url + '/markets'); await page.waitForTimeout(3000); await page.evaluate(() => navigator.serviceWorker.ready);
console.log('perm', await page.evaluate(() => Notification.permission));
let regId = null; cdp.on('ServiceWorker.workerRegistrationUpdated', e => { if (e.registrations[0]) regId = e.registrations[0].registrationId; });
cdp.on('ServiceWorker.workerErrorReported', e => console.log('SWERR', e.errorMessage.errorMessage.slice(0, 120)));
await cdp.send('ServiceWorker.enable'); await page.waitForTimeout(800);
const send = d => cdp.send('ServiceWorker.deliverPushMessage', { origin: url, registrationId: regId, data: JSON.stringify(d) });
const read = () => page.evaluate(async () => (await (await navigator.serviceWorker.ready).getNotifications()).map(n => ({ title: n.title, tag: n.tag, url: n.data && n.data.url, actions: (n.actions || []).map(a => a.action), badge: String(n.badge).split('/').pop() })));
await send({ kind: 'test', title: 'Hello', body: 'Body', tag: 'cm-test', url: '/coin/BTC' }); await page.waitForTimeout(1200);
console.log('test push ->', JSON.stringify(await read()));
await send({ kind: 'target', id: 'abc', ticker: 'BTC', title: 'BTC is above $90,000', body: 'Now $90,250.', tag: 'tgt-abc', url: 'https://evil.example/phish' }); await page.waitForTimeout(1000);
console.log('foreground target push (page visible -> in-app only):', JSON.stringify((await read()).map(n => n.tag)));
await ctx.close(); server.close();
