import { open } from './harness.mjs';
const h = await open({ standalone: false }); const { page, ctx, url, errs } = h;
const bs = await h.browser.newBrowserCDPSession(); await bs.send('Browser.setPermission', { permission: { name: 'notifications' }, setting: 'granted', origin: url });
await page.goto(url + '/markets'); await page.waitForTimeout(3000);
await page.evaluate(() => navigator.serviceWorker.ready);
console.log('perm', await page.evaluate(() => Notification.permission));
const cdp = await ctx.newCDPSession(page);
let regId = null; cdp.on('ServiceWorker.workerRegistrationUpdated', e => { if (e.registrations[0]) regId = e.registrations[0].registrationId; });
cdp.on('ServiceWorker.workerErrorReported', e => console.log('SWERR', JSON.stringify(e.errorMessage).slice(0, 200)));
await cdp.send('ServiceWorker.enable'); await page.waitForTimeout(800);
console.log('regId', regId);
const send = d => cdp.send('ServiceWorker.deliverPushMessage', { origin: url, registrationId: regId, data: JSON.stringify(d) });
await send({ kind: 'test', id: 'abc', title: 'Hello', body: 'Body', tag: 'cm-test', url: '/coin/BTC' });
await page.waitForTimeout(1500);
const read = () => page.evaluate(async () => (await (await navigator.serviceWorker.ready).getNotifications()).map(n => ({ title: n.title, tag: n.tag, url: n.data && n.data.url, actions: (n.actions || []).length, badge: String(n.badge).split('/').pop() })));
console.log('after test push', JSON.stringify(await read()));
await send({ kind: 'test', title: 'x', url: 'https://evil.example/phish', tag: 'e' }); await page.waitForTimeout(1000);
console.log('evil', JSON.stringify(await read()));
console.log(errs);
await h.close();
