import { open } from './harness.mjs';
const h = await open(); const { page, url } = h;
const shot = async (p, name, wait = 2500) => { await page.goto(url + p); await page.waitForTimeout(wait); await page.screenshot({ path: `/tmp/${name}.png` }); };
await shot('/settings', 'settings');
await shot('/convert', 'convert');
await page.click('#cvp-to-btn'); await page.waitForTimeout(700); await page.screenshot({ path: '/tmp/convert-pick.png' });
await shot('/coin/BTC', 'coin', 3500);
await page.goto(url + '/'); await page.waitForTimeout(2500);
await page.click('[aria-label*="enu" i]').catch(() => {}); await page.waitForTimeout(800); await page.screenshot({ path: '/tmp/menu.png' });
await h.close();
