import { open } from './harness.mjs';
import { execSync } from 'node:child_process';
const h = await open(); const { page, url, errs } = h;
page.on('console', m => { if (/DBG/.test(m.text())) console.log(m.text()); });
page.on('framenavigated', f => { if (f === page.mainFrame()) console.log('DBG main navigated', f.url()); });
await page.addInitScript(() => { if (window.top === window) window.__c0 = !!navigator.serviceWorker.controller; });
await page.goto(url + '/app'); await page.waitForTimeout(4000);
await page.reload(); await page.waitForTimeout(4000);
console.log('controller at start:', await page.evaluate(() => !!navigator.serviceWorker.controller), 'origin', await page.evaluate(() => performance.timeOrigin));
await page.click('.app-tabbar a[data-tab="news"]'); await page.waitForTimeout(500);
await page.evaluate(() => { navigator.serviceWorker.addEventListener('controllerchange', () => console.log('DBG shell saw controllerchange')); });
execSync('rm -rf /home/claude/frontend/dist && cp -r /tmp/fe2/dist /home/claude/frontend/dist');
const f = page.frames().find(x => new URL(x.url()).pathname === '/news');
await f.evaluate(async () => { const { updates } = await import('/js/pwa.js'); updates.setMode('manual'); await updates.check(); for (let i = 0; i < 40 && updates.get().status !== 'ready'; i++) await new Promise(r => setTimeout(r, 250)); const g = updates.get(); console.log('DBG status', g.status, g.error, g.latest && g.latest.build); updates.apply(); });
const info = await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return { active: r.active && r.active.state, waiting: !!r.waiting, installing: !!r.installing, ctrl: navigator.serviceWorker.controller && navigator.serviceWorker.controller.state }; });
console.log('reg after apply (immediate):', JSON.stringify(info));
await page.waitForTimeout(1500);
console.log('DBGE', await page.evaluate(() => Math.round(performance.now()) + ' ' + performance.timeOrigin));
await page.waitForTimeout(2500);
const info2 = await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return { active: r.active && r.active.state, waiting: !!r.waiting, ctrl: navigator.serviceWorker.controller && navigator.serviceWorker.controller.state, keys: await caches.keys() }; });
console.log('reg later:', JSON.stringify(info2));
console.log('restore flag:', await page.evaluate(() => sessionStorage.getItem('cm-shell-restore')), 'navtype', await page.evaluate(() => performance.getEntriesByType('navigation')[0].type), 'nframes', page.frames().length);
console.log('cfg', await page.evaluate(() => JSON.stringify(window.CRYPTOMIUM) + ' ' + document.querySelector('script[src*=config]').getAttribute('src') + ' sw:' + (navigator.serviceWorker.controller && navigator.serviceWorker.controller.scriptURL)));
console.log('DBGC', JSON.stringify(await page.evaluate(async () => { const out = {}; for (const k of await caches.keys()) { const c = await caches.open(k); const ks = await c.keys(); out[k] = ks.length; } const r = await caches.match('/config.js'); out.cfg = r ? (await r.text()).slice(-90) : null; const net = await fetch('/config.js', {cache:'no-store'}); out.net = (await net.text()).slice(-90); const a = await caches.match('/app'); out.appHasV = a ? ((await a.text()).match(/config\.js\?v=\w+/)||[])[0] : null; return out; })));
console.log('DBGD', await page.evaluate(async () => (await (await fetch('/app')).text()).match(/config\.js\?v=\w+/)[0] + ' | live html: ' + document.querySelector('script[src*=config]').getAttribute('src') + ' | t=' + Math.round(performance.now())));
console.log('DBGF c0=', await page.evaluate(() => window.__c0));
console.log('origin after:', await page.evaluate(() => performance.timeOrigin), 'build', await page.evaluate(() => window.CRYPTOMIUM.build), 'url', page.url());
console.log(errs);
await h.close();
