import { open } from './harness.mjs';
import { execSync } from 'node:child_process';
const h = await open(); const { page, url, errs } = h;
page.on('console', m => { if (/DBG/.test(m.text())) console.log(m.text()); });
await page.goto(url + '/app'); await page.waitForTimeout(4000);
await page.reload(); await page.waitForTimeout(4000);
console.log('controller at start:', await page.evaluate(() => !!navigator.serviceWorker.controller), 'origin', await page.evaluate(() => performance.timeOrigin));
await page.evaluate(() => { navigator.serviceWorker.addEventListener('controllerchange', () => console.log('DBG shell saw controllerchange')); });
execSync('rm -rf /home/claude/frontend/dist && cp -r /tmp/fe2/dist /home/claude/frontend/dist');
const f = page.frames().find(x => new URL(x.url()).pathname === '/markets');
await f.evaluate(async () => { const { updates } = await import('/js/pwa.js'); updates.setMode('manual'); await updates.check(); for (let i = 0; i < 40 && updates.get().status !== 'ready'; i++) await new Promise(r => setTimeout(r, 250)); const g = updates.get(); console.log('DBG status', g.status, g.error, g.latest && g.latest.build); updates.apply(); });
const info = await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return { active: r.active && r.active.state, waiting: !!r.waiting, installing: !!r.installing, ctrl: navigator.serviceWorker.controller && navigator.serviceWorker.controller.state }; });
console.log('reg after apply (immediate):', JSON.stringify(info));
await page.waitForTimeout(4000);
const info2 = await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return { active: r.active && r.active.state, waiting: !!r.waiting, ctrl: navigator.serviceWorker.controller && navigator.serviceWorker.controller.state, keys: await caches.keys() }; });
console.log('reg later:', JSON.stringify(info2));
console.log('origin after:', await page.evaluate(() => performance.timeOrigin), 'build', await page.evaluate(() => window.CRYPTOMIUM.build), 'url', page.url());
console.log(errs);
await h.close();
